[version]
current = "0.3.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
'''

[git]
tag_template = "v{new_version}"
message_template = "Bump to {new_version}"

[[file]]
src = "Cargo.toml"
search = 'version = "{current_version}"'

[[hook]]
name = "Check changelog"
cmd = "python tools/check-changelog.py {new_version}"
